PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> 
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
 
# the first source:
PREFIX bm: <http://www.grsu.by/net/OdTMBaseThreatModel#> 
# another one:
PREFIX : <http://www.grsu.by/net/OdTMIntegratedModel#> 

SELECT (?a as ?restrictions) (count(?c) as ?threats) 
FROM <../ttl/OdTMIntegratedModel.ttl>
WHERE
{
   ?a rdfs:subClassOf ?b .
   ?b owl:onProperty <http://www.grsu.by/net/OdTMBaseThreatModel#isAffectedBy> ;
      owl:hasValue ?c .
}
group by ?a
ORDER BY desc(?threats)


