PREFIX b: <http://www.grsu.by/net/OdTMBaseThreatModel#> 
PREFIX : <http://www.grsu.by/net/OdTMDockerComposeModel#> 
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> 
PREFIX owl: <http://www.w3.org/2002/07/owl#> 

# ???
# (isTargetOf HTTPFlow) and (isTargetOf HTTPSFlow)

SELECT ?target
WHERE {
  ?flow rdf:type :HTTPFlow .
  ?flow1 rdf:type :HTTPSFlow .
  ?target b:isTargetOf ?flow .
  ?target b:isTargetOf ?flow1 .

}