PREFIX b: <http://www.grsu.by/net/OdTMBaseThreatModel#> 
PREFIX : <http://www.grsu.by/net/OdTMDockerComposeModel#> 
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> 
PREFIX owl: <http://www.w3.org/2002/07/owl#> 

# template: HTTPServer <-> Database

SELECT ?target ?target1
WHERE {
   ?target rdf:type :HTTPServer .

   ?target1 rdf:type :Database .
   ?target1 b:relates ?target .


}
ORDER BY ?target