PREFIX b: <http://www.grsu.by/net/OdTMBaseThreatModel#> 
PREFIX : <http://www.grsu.by/net/OdTMDockerComposeModel#> 
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> 
PREFIX owl: <http://www.w3.org/2002/07/owl#> 

# 
# template: user -> WebApplication -> Database

SELECT ?source ?flow ?target ?flow1 ?target1
WHERE {
   ?target rdf:type :WebApplication .

   ?flow b:hasSource :user ;
         b:hasTarget ?target .

   ?source b:isSourceOf ?flow .

   ?target b:isSourceOf ?flow1 .
   ?flow1 b:hasTarget ?target1 .

   ?target1 rdf:type :Database .

}
ORDER BY ?target