PREFIX b: <http://www.grsu.by/net/OdTMBaseThreatModel#> 
PREFIX : <http://www.grsu.by/net/OdTMDockerComposeModel#> 
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> 
PREFIX owl: <http://www.w3.org/2002/07/owl#> 

# ok
# (hasTarget :dockerSocket) and (ReadOnlyFlow)

SELECT ?source ?flow ?target
WHERE {
  ?flow b:hasTarget :dockerSocket ;
        rdf:type :ReadOnlyFlow .
  ?source b:isSourceOf ?flow .
  ?target b:isTargetOf ?flow .
}
ORDER BY ?source