PREFIX b: <http://www.grsu.by/net/OdTMBaseThreatModel#> 
PREFIX : <http://www.grsu.by/net/OdTMDockerComposeModel#> 
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> 
PREFIX owl: <http://www.w3.org/2002/07/owl#> 

# ok
# Process is HTTPServer and HTTPSServer

SELECT ?process
WHERE {
  ?process rdf:type :HTTPServer ;
           rdf:type :HTTPSServer .
}
ORDER BY ?process