PREFIX b: <http://www.grsu.by/net/OdTMBaseThreatModel#> 
PREFIX : <http://www.grsu.by/net/OdTMDockerComposeModel#> 
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> 
PREFIX owl: <http://www.w3.org/2002/07/owl#> 

# ok
# (isSourceOf SensitiveHostPath) and (isSourceOf ReadWriteFlow)

SELECT ?source ?flow ?target
WHERE {
  ?flow rdf:type :SensitiveHostPath ;
        rdf:type :ReadWriteFlow .
  ?source b:isSourceOf ?flow .
  ?target b:isTargetOf ?flow .
}
ORDER BY ?source